#! /bin/bash

usage () {
    echo "$0 - a script to build a rpm file for node."
    echo "Usage: $0 <rpmbuilder-directory> <release>"
}

if [ -z "$1" -o -z "$2" ]; then
    usage
    exit 1
fi

set -e

readonly RPMBUILDER="$1"
readonly RELEASE="$2"
readonly VERSION=$(git branch | cut -f2 -d' ' | tr -d '-' )

echo "Will package ${VERSION}, release ${RELEASE}."
git archive --prefix "node-${VERSION}/" HEAD | gzip >"${RPMBUILDER}/rpmbuild/SOURCES/node-${VERSION}.tar.gz"
cat ./node.spec | sed -e "s/@@@VERSION@@@/${VERSION}/g" -e "s/@@@RELEASE@@@/${RELEASE}/g" >"${RPMBUILDER}/rpmbuild/SPECS/node.spec"

echo "Build rpms"
rpmbuild -bb "${RPMBUILDER}/rpmbuild/SPECS/node.spec"
